### PR TITLE
Add codecov integration

### PR DESCRIPTION
**Pull request by LoyVanBeek**

### CODE REVIEW

**Comment by Rayman** [comment]
Met https://codeclimate.com/github/tue-robotics/robot_skills kun je zowel coverage als code analysis doen (pep8). Is dat niet iets?

**Comment by LoyVanBeek** [comment]
Both look good, I don't have a preference. 
Main issue right now is that coverage run blabla.py doesn't generate report. 
I think this is due to only running doctests?

**Comment by LoyVanBeek** [comment]
CodeClimate indeed does some nice checking as well. Especially the complexity measures are nice, they highlight exactly what is too complex right now.

**Comment by LoyVanBeek** [comment]
But CodeClimate doesn't support coverage for Python yet, only Ruby, JavaScript and PHP. 
So add both!

**Comment by Rayman** [comment]
Both :+1:

**Pull request merged**
